databases:
  - name: nocapston
    databaseName: nocapston
    user: nocapston_user

services:
  - type: web
    name: TRI-LC ENTERPRISES
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn corepro.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TRI-LC ENTERPRISES
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4